# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-22 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20180407_1043'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newsletter',
            managers=[
            ],
        ),
    ]
